id: P4EBD612E
initial_creation_type: ocr
source_metadata:
  volumes:
    bb5cfb82c52e457d9b4f532aee0b2715:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་བསྟོད་པ་རྐང་པ་བརྒྱད་པ།
      total_pages: 1856
      volume_number: 14
